---
kind: pipeline
name: default
type: docker

platform:
  os: linux

steps:
  - name: build
    image: codestation/drone-docker
    settings:
      repo: registry.megpoid.xyz/codestation/socat
      tags: latest
      registry: registry.megpoid.xyz
      buildkit: true
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password

  - name: update
    image: plugins/webhook
    settings:
      urls: http://updater:8000/apis/swarm/v1/update
      token_value:
        from_secret: updater_appkey
      template: |
        {
          "images": [
            "registry.megpoid.xyz/codestation/socat"
          ]
        }

trigger:
  branch:
    - master
